### ISSUE TITLE
باگ های عجیب

### ISSUE THREAD

**Issue by younesveisi1374** [ResoneAt/R-Social-media#50]
سلام و درود.یک مطلب بگم که در این پروژه یکسری ایرادات در قسمت بک اند داره که باید برطرف بشه در خصوص superuser و منوی سمت چپ اکانت که لاگین صورت میگیره.همچنین اینکه فرمت دیتابیس خیلی عجیب ساخته میشه و جای اسم و فرمت برعکس هست مثلا وقتی پروژه ران میشه دیتابیس با اسم db.sqlite3 ساخته میشه که اشتباهه و باید با اسم sqlite3.db ساخته بشه.لطفا ایرادات رو رفع کنید تا نمونه کاربهتر و کاملتری داشته باشید
همچنین هیچ کدوم از گزینه ها و دکمه های سایت رسانه اجتماعی کار نمیکنه کلا و فقط یک فرانت اند ساده هستش و بک اند نداره من هرچی تلاش کردم نتونستم کاری کنم.

**Comment by ResoneAt** [comment]
سلام جناب ویسی عزیز ... بله حتما بخش بکند را و برسی و نتیجه را خدمتتون اعلام میکنم ... 
بخش فرانتش در دست توسعس و این صفحه ای که مشاهده میکنین در صفحه home ، کاملا جدید هستش و به زودی تکمیل میشه

**Comment by younesveisi1374** [comment]
سلام و درود وقت کردید که نگاهی باگ های برنامه تون بندازید؟

**Comment by ResoneAt** [comment]
سلام جناب ویسی ... من برنامه رو چک کردم مشکل مربوط به superuser حل کردم ولی مواردی که راجب فرمت دیتابیس فرمودین هیچ مشکلی نداشت  ...

**Comment by younesveisi1374** [comment]
> سلام جناب ویسی ... من برنامه رو چک کردم مشکل مربوط به superuser حل کردم ولی مواردی که راجب فرمت دیتابیس فرمودین هیچ مشکلی نداشت ...

بسیار هم عالی
شاید مشکل از اجرای برنامه سیستم بوده
امیداورم موفق باشید.
